name: Production Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Deploy to Production
        run: |
          ${{ secrets.SSH_COMMAND }} << 'EOF'
            cd ~/cozy-bot
            git pull origin main
            docker-compose --profile prod down --remove-orphans
            docker rmi $(docker images | grep cozy-discord-bot | awk '{print $3}') 2>/dev/null || true
            docker-compose --profile prod up -d --build
          EOF
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

