  name: Production Deploy
  on:
    push:
      branches: [ main ]

  jobs:
    deploy:
      runs-on: ubuntu-latest
      environment: production
      steps:
        - name: 🚀 Setup SSH
          uses: webfactory/ssh-agent@v0.9.0
          with:
            ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        
        - name: 🔑 Add SSH host key
          run: |
            mkdir -p ~/.ssh
            ssh-keyscan -p 2248 90.60.191.159 >> ~/.ssh/known_hosts

        - name: 🔍 Test SSH & Docker access
          run: |
            ssh -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} 'docker --version && docker ps'

        
        - name: 🛡️ Deploy to Production
          run: |
            ssh -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} 'bash -l -c "cd ~/cozy-bot && git stash || true && git checkout main && git pull origin main && chmod +x deploy-prod.sh && ./deploy-prod.sh"'

            